"""empty message

Revision ID: 27c36be70f5e
Revises: 7ce26fe09901
Create Date: 2024-10-11 13:16:56.726736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c36be70f5e'
down_revision: Union[str, None] = '7ce26fe09901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('groups_tasks_id_fkey', 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'tasks', ['tasks_id'], ['task_id'])
    op.add_column('tasks', sa.Column('task_id', sa.Integer(), nullable=False))
    op.drop_column('tasks', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tasks_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_column('tasks', 'task_id')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key('groups_tasks_id_fkey', 'groups', 'tasks', ['tasks_id'], ['id'])
    # ### end Alembic commands ###
