"""Initial

Revision ID: 9d0220dc34ad
Revises: ff14471f4e27
Create Date: 2024-10-21 15:16:39.074802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0220dc34ad'
down_revision: Union[str, None] = 'ff14471f4e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'Users', ['user_id'], ['id'])
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'user_id')
    # ### end Alembic commands ###
