"""Migration Done

Revision ID: ad58998010d0
Revises: ae096a54d7c8
Create Date: 2024-10-10 18:38:28.795619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad58998010d0'
down_revision: Union[str, None] = 'ae096a54d7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('progress_tasks', sa.Integer(), nullable=False),
    sa.Column('archived_tasks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('groups', sa.Column('tasks_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'tasks', ['tasks_id'], ['id'])
    op.add_column('tasks', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'group_id')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'tasks_id')
    op.drop_table('Users')
    # ### end Alembic commands ###
